version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "11:00"
      timezone: "America/New_York"
    groups:
      cargo:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "11:00"
      timezone: "America/New_York"
    groups:
      github-actions:
        patterns:
          - "*"
